/// Generated by AssetsRefGenerator on 2021/05/31
class Res {
  static const String googleLogo = "assets/images/google-logo.png";
  static const String facebookLogo = "assets/images/facebook-logo.png";
}
